import { Check, FileUp, LockKeyhole } from 'lucide-react';
import type { AppState, Task } from '../domain/types';
import type { AppView } from './AppShell';

export function CreateTaskWizard({ onCreated, onNavigate, state }: { onCreated: (task: Task) => void; onNavigate: (view: AppView) => void; state: AppState }) {
  const steps = ['基本信息', '导入文档', '标签体系', '人员分配'];
  const create = () => onCreated({ id: `task-${Date.now()}`, name: '新建法律论证标注任务', description: '待补充任务说明', guideVersion: 'v1.1', stage: 'draft', documentIds: [], annotatorIds: [], adjudicatorIds: ['u-owner'], createdAt: new Date().toISOString() });
  return <div className="page-wrap narrow"><header className="page-header"><div><p className="eyebrow">NEW PROJECT / SETUP</p><h1>创建标注任务</h1><p className="lede">从文书范围到人员分配，一次设定清楚。</p></div><button className="text-button" onClick={() => onNavigate('overview')}>取消</button></header><div className="wizard-steps">{steps.map((step, index) => <div className={`wizard-step ${index === 0 ? 'current' : ''}`} key={step}><span>{index + 1}</span><strong>{step}</strong>{index < steps.length - 1 && <i />}</div>)}</div><div className="wizard-body card"><section className="wizard-section"><div className="section-icon"><FileUp size={18} /></div><div><p className="eyebrow">STEP 01 / BASIC INFO</p><h2>先给这次标注一个清晰的名字</h2><p className="helper">名称会出现在所有成员的任务列表和导出记录里。</p><label>任务名称<input defaultValue="新建法律论证标注任务" /></label><label>任务说明<textarea defaultValue="用于标注裁判理由中的命题类型与论证关系。" /></label><div className="two-col"><label>案例类型<select defaultValue="普通案例"><option>普通案例</option><option>参考案例</option><option>指导性案例</option></select></label><label>标注指南版本<div className="locked-input"><LockKeyhole size={15} />v1.1 中文裁判文书<span>已锁定</span></div></label></div></div></section><div className="wizard-preview"><div><p className="eyebrow">NEXT STEPS</p><strong>文档、标签和人员将在下一步配置</strong><span>当前工作台用户：{state.users[state.currentUserId].name}</span></div><button className="primary-button" onClick={create}><Check size={16} />保存并继续</button></div></div></div>;
}
