import { CheckCircle2, Download, FileJson, Image, Package, Table2 } from 'lucide-react';
import type { AppState } from '../domain/types';
import type { AppView } from './AppShell';
import { buildExportRecord, serializeJson } from '../domain/exporters';

export function ExportView({ state, onExport, onNavigate }: { state: AppState; onExport: (record: ReturnType<typeof buildExportRecord>) => void; onNavigate: (view: AppView) => void }) {
  const task = state.tasks['task-1']; const version = state.annotationVersions['version-a'];
  const options = [{ format: 'JSON' as const, name: '结构化 JSON', detail: '命题、字符索引与关系定义', icon: FileJson, file: 'argument-result.json' }, { format: 'Excel' as const, name: '标注数据表', detail: '命题列表、标签与关系矩阵', icon: Table2, file: 'argument-result.xlsx' }, { format: 'PNG' as const, name: '论证图示', detail: '适合汇报和评审的图片', icon: Image, file: 'argument-map.png' }, { format: 'ZIP' as const, name: '完整压缩包', detail: '包含全部格式与指南版本', icon: Package, file: 'argument-result.zip' }];
  const download = (option: typeof options[number]) => { const record = buildExportRecord(option.format, option.file, state.currentUserId); onExport(record); if (option.format === 'JSON') { const blob = new Blob([serializeJson(version, task)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = option.file; anchor.click(); URL.revokeObjectURL(url); } };
  return <div className="page-wrap"><div className="breadcrumb">任务详情 <span>/</span> 结果输出</div><header className="page-header compact"><div><p className="eyebrow">FINAL RESULT / READ ONLY</p><h1>结果输出</h1><p className="lede">最终版本已确认，导出后将不可再编辑。</p></div><span className="read-only-badge"><CheckCircle2 size={15} />最终版本</span></header><div className="final-summary card"><div><p className="eyebrow">FINAL ANNOTATION</p><h2>劳务合同纠纷论证结构试标</h2><span>指南 v1.1 · 1 份文书 · {version.propositions.length} 个命题 · {version.relations.length} 个关系</span></div><button className="outline-button" onClick={() => onNavigate('adjudicate')}>查看裁定记录</button></div><section className="export-grid">{options.map((option) => { const Icon = option.icon; return <button className="export-card" key={option.format} onClick={() => download(option)}><div className="export-icon"><Icon size={20} /></div><div><strong>{option.name}</strong><span>{option.detail}</span></div><Download size={16} className="export-arrow" /></button>; })}</section><section className="download-history card"><div className="card-title"><div><p className="eyebrow">EXPORT HISTORY</p><h2>下载记录</h2></div><span className="muted">{state.exportRecords.length} 次导出</span></div>{state.exportRecords.length === 0 ? <div className="empty-history">导出文件后，下载用户、格式和时间会显示在这里。</div> : state.exportRecords.map((record) => <div className="history-row" key={record.id}><CheckCircle2 size={16} /><strong>{record.filename}</strong><span>{record.format}</span><span>{state.users[record.userId]?.name}</span><span>{new Date(record.createdAt).toLocaleString('zh-CN')}</span></div>)}</section></div>;
}
