import { Plus, Trash2 } from 'lucide-react';
import { primaryLabels, secondaryLabels } from '../domain/labels';
import type { AppState, AnnotationVersion, Proposition } from '../domain/types';
import type { AppAction } from '../domain/store';

export function PropositionPanel({ state, version, selectedId, onSelect, onDispatch, readOnly }: { state: AppState; version: AnnotationVersion; selectedId?: string; onSelect: (id: string) => void; onDispatch: (action: AppAction) => void; readOnly: boolean }) {
  const selected = version.propositions.find((item) => item.id === selectedId) ?? version.propositions[0];
  return <section className="workspace-panel prop-panel"><div className="panel-heading"><div><p className="eyebrow">ANNOTATION / PROPOSITIONS</p><h2>命题属性</h2></div>{!readOnly && <button className="small-button" onClick={() => onDispatch({ type: 'add-proposition', versionId: version.id, proposition: { id: `p-${Date.now()}`, number: version.propositions.length + 1, text: '新命题', start: 0, end: 3 } })}><Plus size={14} />添加</button>}</div><div className="prop-list">{version.propositions.map((item) => <button key={item.id} className={`prop-item ${selected?.id === item.id ? 'selected' : ''}`} onClick={() => onSelect(item.id)}><span className="prop-number">{String(item.number).padStart(2, '0')}</span><span className="prop-copy"><strong>{item.text}</strong><span>{item.primaryLabel ?? '未分类'} {item.secondaryLabel ? `· ${item.secondaryLabel}` : ''}</span></span><i className={`label-dot ${item.primaryLabel?.toLowerCase() ?? 'empty'}`} /></button>)}</div>{selected && <div className="prop-editor"><div className="editor-label">当前命题 <span>P{selected.number}</span></div><textarea value={selected.text} disabled={readOnly} onChange={(event) => onDispatch({ type: 'update-proposition', versionId: version.id, propositionId: selected.id, patch: { text: event.target.value, end: selected.start + event.target.value.length } })} /><div className="index-pair"><span>start <strong>{selected.start}</strong></span><span>end <strong>{selected.end}</strong></span></div><label>一级标签<select disabled={readOnly} value={selected.primaryLabel ?? ''} onChange={(event) => onDispatch({ type: 'update-proposition', versionId: version.id, propositionId: selected.id, patch: { primaryLabel: event.target.value as Proposition['primaryLabel'], secondaryLabel: undefined } })}><option value="">选择标签</option>{primaryLabels.map((label) => <option key={label.code} value={label.code}>{label.code} · {label.name}</option>)}</select></label>{selected.primaryLabel && ['GM', 'SM'].includes(selected.primaryLabel) && <label>二级标签<select disabled={readOnly} value={selected.secondaryLabel ?? ''} onChange={(event) => onDispatch({ type: 'update-proposition', versionId: version.id, propositionId: selected.id, patch: { secondaryLabel: event.target.value } })}><option value="">选择子标签</option>{secondaryLabels[selected.primaryLabel as 'GM' | 'SM'].map((label) => <option key={label.code} value={label.code}>{label.code} · {label.name}</option>)}</select></label>}{!readOnly && <button className="danger-button" onClick={() => onDispatch({ type: 'remove-proposition', versionId: version.id, propositionId: selected.id })}><Trash2 size={14} />删除并重新创建</button>}</div>}</section>;
}
