import { ArrowRight, FileText, GitCompare, LockKeyhole, Users } from 'lucide-react';
import type { AppState } from '../domain/types';
import type { AppView } from './AppShell';

const stageText = { draft: '草稿', annotating: '标注中', adjudicating: '待裁定', adjudicated: '已裁定', exported: '已导出' } as const;

export function TaskDetail({ state, onNavigate }: { state: AppState; onNavigate: (view: AppView) => void }) {
  const task = Object.values(state.tasks)[0]; const doc = state.documents[task.documentIds[0]];
  return <div className="page-wrap"><div className="breadcrumb">任务总览 <span>/</span> {task.name}</div><header className="page-header compact"><div><p className="eyebrow">TASK / {task.guideVersion}</p><h1>{task.name}</h1><p className="lede">{task.description}</p></div><span className={`stage stage-${task.stage}`}>{stageText[task.stage]}</span></header><div className="stage-tracker">{[['draft','创建'],['annotating','标注'],['adjudicating','裁定'],['adjudicated','确认'],['exported','输出']].map(([key,label], index) => <div className={`tracker-item ${key === task.stage ? 'active' : ''}`} key={key}><span>{String(index + 1).padStart(2, '0')}</span><strong>{label}</strong>{index < 4 && <i />}</div>)}</div><section className="detail-grid"><div className="card doc-card"><div className="card-title"><div><p className="eyebrow">DOCUMENTS / 01</p><h2>待处理文书</h2></div><button className="icon-button"><FileText size={16} /></button></div><div className="doc-row"><div className="doc-icon large"><FileText size={20} /></div><div><strong>{doc?.name}</strong><span>{doc?.caseType} · 裁判理由 {doc?.reasoningText.length} 字符</span></div><span className="status-dot green" /></div><div className="progress-line"><span style={{ width: '58%' }} /></div><div className="doc-meta"><span>标注进度 <strong>2 / 2</strong></span><span>裁定状态 <strong>待确认</strong></span></div><button className="wide-button" onClick={() => onNavigate('annotate')}>打开标注工作区 <ArrowRight size={16} /></button></div><div className="card people-card"><div className="card-title"><div><p className="eyebrow">COLLABORATORS</p><h2>参与人员</h2></div><Users size={18} /></div><div className="person-list">{['u-annotator-1','u-annotator-2','u-owner'].map((id) => <div className="person-row" key={id}><div className="avatar small">{state.users[id].name.slice(0,1)}</div><div><strong>{state.users[id].name}</strong><span>{state.users[id].roles[0]}</span></div><span className="person-state">{id === 'u-owner' ? '裁定者' : '已提交'}</span></div>)}</div><div className="locked-note"><LockKeyhole size={15} />标签体系已锁定，使用指南 v1.1</div></div></section><section className="action-strip"><div><GitCompare size={18} /><div><strong>有 3 处标注差异等待裁定</strong><span>包括 1 处边界、1 处标签和 1 处关系差异</span></div></div><button className="primary-button" onClick={() => onNavigate('adjudicate')}>进入裁定 <ArrowRight size={16} /></button></section></div>;
}
