import { ArrowUpRight, FileText, Plus, Users } from 'lucide-react';
import type { AppState } from '../domain/types';
import type { AppView } from './AppShell';

const stageText = { draft: '草稿', annotating: '标注中', adjudicating: '待裁定', adjudicated: '已裁定', exported: '已导出' } as const;

export function TaskOverview({ state, onNavigate }: { state: AppState; onNavigate: (view: AppView) => void }) {
  const tasks = Object.values(state.tasks);
  return <div className="page-wrap"><header className="page-header"><div><p className="eyebrow">ARGUMENTATION WORKSPACE / 01</p><h1>任务总览</h1><p className="lede">把裁判理由拆成可检验的命题和关系。</p></div><button className="primary-button" onClick={() => onNavigate('create')}><Plus size={16} />创建新任务</button></header><section className="signal-row"><div className="signal-card"><span>进行中的任务</span><strong>{tasks.filter((task) => task.stage !== 'exported').length.toString().padStart(2, '0')}</strong><small>个任务在工作台内</small></div><div className="signal-card"><span>待裁定文档</span><strong>01</strong><small>需要专家确认</small></div><div className="signal-card warm"><span>当前指南</span><strong>v1.1</strong><small>标签体系已锁定</small></div></section><section className="section-heading"><div><p className="eyebrow">YOUR CORPUS</p><h2>标注任务</h2></div><div className="filter-pills"><button className="pill active">全部</button><button className="pill">标注中</button><button className="pill">待裁定</button></div></section><div className="task-table card"><div className="table-head"><span>任务名称</span><span>阶段</span><span>文档 / 标注</span><span>指南</span><span>最近更新</span><span /></div>{tasks.map((task) => <button className="task-row" key={task.id} onClick={() => onNavigate('task')}><div className="task-name"><div className="doc-icon"><FileText size={17} /></div><div><strong>{task.name}</strong><span>{task.description}</span></div></div><div><span className={`stage stage-${task.stage}`}>{stageText[task.stage]}</span></div><div className="metric"><strong>{task.documentIds.length}</strong><span>文档</span><strong>{task.annotatorIds.length}</strong><span>标注员</span></div><div className="mono">{task.guideVersion}</div><div className="muted">今天 10:42</div><ArrowUpRight size={18} className="row-arrow" /></button>)}</div><div className="overview-note"><Users size={17} /><span>多人独立标注后，裁定者会在同一文书上看到每个版本的边界、标签与关系差异。</span></div></div>;
}
